import type {
  NavItem,
  ServiceData,
  PortfolioProject,
  FAQItem,
  StatItem,
  TimelineItem,
  Team,
  FeaturedClient,
  MaturityQuestion,
} from "@/types";

// ===== Company Info =====
export const COMPANY = {
  name: "시앤피컨설팅",
  nameEn: "CNP Consulting",
  division: "직업능력컨설팅본부",
  ceo: "조세형",
  tel: "02-6326-1444",
  email: "sjlee@cnp.re.kr",
  bizNumber: "119-86-57311",
  address: "(08506) 서울시 금천구 가산디지털1로 131, B동 1202호(BYC하이시티)",
  website: "https://www.cnp.re.kr",
  tagline: "Competency & Performance",
  slogan: "직무 중심 인사혁신, 역량 기반 인재개발, AI Transformation",
};

// ===== Navigation =====
export const NAV_ITEMS: NavItem[] = [
  { label: "본부소개", href: "/about" },
  {
    label: "서비스",
    href: "/services",
    children: [
      { label: "HRM 컨설팅", href: "/services/hrm" },
      { label: "공공기관 HR 컨설팅", href: "/services/public-hr" },
      { label: "HRD 컨설팅", href: "/services/hrd" },
      { label: "AX 컨설팅", href: "/services/ax" },
    ],
  },
  { label: "사업실적", href: "/portfolio" },
  { label: "문의", href: "/contact" },
];

// ===== Home Stats =====
export const HOME_STATS: StatItem[] = [
  { value: "150", suffix: "+", label: "프로젝트 수행" },
  { value: "80", suffix: "+", label: "고객 기관" },
  { value: "15", suffix: "yr+", label: "전문 경력" },
  { value: "4", suffix: "대 분야", label: "HRM·공공HR·HRD·AX" },
];

// ===== Services Overview (for home & hub) =====
export const SERVICES_OVERVIEW = [
  {
    number: "01",
    id: "hrm",
    title: "HRM 컨설팅",
    subtitle: "직무중심 인적자원관리",
    team: "",
    description:
      "직무분석에서 직무평가, 보수체계 설계, 성과관리까지. 직무 중심 인사혁신의 전 과정을 체계적으로 설계합니다.",
    highlights: [
      "직무분석 및 분류체계 수립",
      "직무체계 설계",
      "직무평가 기반 직무등급 설계",
      "직무중심 보수체계 전환",
      "성과관리체계 및 조직설계",
    ],
    href: "/services/hrm",
  },
  {
    number: "02",
    id: "public-hr",
    title: "공공기관 HR 컨설팅",
    subtitle: "공공부문 인사혁신 전문",
    team: "",
    description:
      "공공기관 직무중심 인사제도 개편, 조직진단, 경영전략 수립부터 경영평가 대응까지. 공공부문 HR 혁신을 지원합니다.",
    highlights: [
      "직무중심 인사제도 개편(채용·평가·직무급 등)",
      "조직·인력 운영진단",
      "중장기 경영전략 수립",
      "경영평가 대응 지원",
    ],
    href: "/services/public-hr",
  },
  {
    number: "03",
    id: "hrd",
    title: "HRD 컨설팅",
    subtitle: "체계적 인재개발 솔루션",
    team: "",
    description:
      "직무분석·역량모델링·Skill 기반 교육체계 수립부터 교육로드맵 개발, 성과관리까지. 조직의 인재개발 전 과정을 설계합니다.",
    highlights: [
      "기업 맞춤형 교육체계 수립(직무분석·역량모델링·Skill 기반)",
      "교육로드맵 및 교육과정 개발",
      "교육운영 및 성과관리 체계 구축",
      "직무·경력·조직 개발 컨설팅",
    ],
    href: "/services/hrd",
  },
  {
    number: "04",
    id: "ax",
    title: "AX 컨설팅",
    subtitle: "AI Transformation",
    team: "",
    description:
      "AI 전환 수준 진단부터 전략 수립, Skill Set 구축, 워크플로우 재설계까지. 사람 중심의 AI 전환을 설계합니다.",
    highlights: [
      "AX(AI 전환) 수준 진단",
      "AX 전략 및 실행 로드맵 수립",
      "AI 역량 및 Skill Set 구축",
      "AI 활용 워크플로우 재설계",
      "AX 실행역량 강화 교육훈련(PBL)",
    ],
    href: "/services/ax",
  },
];

// ===== HRM Service Detail =====
export const HRM_SERVICE: ServiceData = {
  id: "hrm",
  tag: "HRM",
  tagColor: "primary",
  team: "HR솔루션팀",
  title: "HRM — 직무중심 인사관리",
  subtitle: "직무분석에서 보수체계 전환까지, 직무중심 인사혁신",
  description:
    "직무분석 및 분류체계 수립부터 직무체계 설계, 직무평가 기반 직무등급 설계, 직무중심 보수체계 전환, 성과관리체계 및 조직설계까지. 민간기업과 공공기관의 직무 중심 인사혁신 전 과정을 설계합니다.",
  items: [
    {
      icon: "ClipboardList",
      title: "직무분석 및 분류체계 수립",
      description: "직무정보 수집, 과업 목록 작성, 직무기술서(JD) 및 분류체계 설계까지 체계적 직무분석 수행",
      methodology: "과업목록법(Task Inventory), DACUM, 현장 인터뷰·설문 병행 분석",
      deliverables: ["직무기술서(JD)", "직무분류체계표", "직무명세서"],
    },
    {
      icon: "Layers",
      title: "직무체계 설계",
      description: "직무군·직무·직위 등 조직의 직무체계를 설계하고, 직무 간 관계와 직급-직무 연계 구조 수립",
      methodology: "직무조사, 직무체계 설계 워크숍, 직무분류 프레임워크",
      deliverables: ["직무체계도", "직무-직급 연계표", "직무기술서"],
    },
    {
      icon: "Scale",
      title: "직무평가 기반 직무등급 설계",
      description: "참여형 평가방법론을 활용한 직무의 상대적 가치 평가 및 직무등급 체계 설계",
      methodology: "요소비교법·점수법 기반 참여형 평가 워크숍",
      deliverables: ["직무평가 보고서", "직무등급 체계표", "등급별 직무 매핑표"],
    },
    {
      icon: "Wallet",
      title: "직무중심 보수체계 전환",
      description: "연공급에서 직무급으로의 전환 로드맵 수립 및 급여 시뮬레이션",
      methodology: "직무급 전환 시뮬레이션, Pay Band 설계, 기재부 가이드라인 연계",
      deliverables: ["보수체계 설계서", "급여 시뮬레이션 결과", "전환 로드맵"],
    },
    {
      icon: "Building2",
      title: "성과관리체계 및 조직설계",
      description: "성과관리체계 구축, 적정인력 산정, 기능-역할 정렬을 통한 효율적 조직 구조 설계",
      methodology: "성과지표(KPI) 설계, 기능분석, 업무량 조사, BPR",
      deliverables: ["성과관리체계 설계서", "적정인력 산정 보고서", "조직개편안"],
    },
  ],
  process: [
    { number: "01", title: "진단", description: "현황 분석 및 이슈 도출" },
    { number: "02", title: "설계", description: "직무체계 및 제도 설계" },
    { number: "03", title: "도입", description: "시범 적용 및 조정" },
    { number: "04", title: "안정화", description: "정착 지원 및 모니터링" },
  ],
  stats: [
    { value: "50", suffix: "+", label: "직무분석 프로젝트" },
    { value: "30", suffix: "+", label: "직무급 전환 컨설팅" },
    { value: "40", suffix: "+", label: "공공기관 인사관리" },
    { value: "15", suffix: "yr+", label: "전문 수행 경력" },
  ],
  cta: { text: "직무분석 컨설팅 상담 신청", href: "/contact" },
};

// ===== HRD Service Detail =====
export const HRD_SERVICE: ServiceData = {
  id: "hrd",
  tag: "HRD",
  tagColor: "green",
  team: "HR솔루션팀",
  title: "HRD — 체계적 인재개발",
  subtitle: "DACUM·CBC·NCS 기반 직무분석, 역량모델링, Skill 기반 체계적 HRD 컨설팅",
  description:
    "기업 맞춤형 교육체계 수립(직무분석·역량모델링·Skill 기반)에서 출발하여, 교육로드맵 및 교육과정 개발, 교육운영·성과관리 체계 구축, 직무·경력·조직 개발 컨설팅까지. 데이터와 검증된 방법론으로 인재개발 전 영역을 설계합니다.",
  items: [
    {
      icon: "GraduationCap",
      title: "기업 맞춤형 교육체계 수립",
      description: "직무분석·역량모델링·Skill 기반으로 기업 특성에 맞는 교육 아키텍처를 설계하고, 직급·직무별 교육 로드맵 및 경력개발경로(CDP)를 연계합니다.",
      methodology: "NCS 능력단위 매핑, TNI(교육 니즈 분석), CBC(역량기반 교육과정) 설계, ADDIE 모델",
      deliverables: ["교육체계도", "교육과정 프로파일", "NCS 매핑표", "CDP 연계 교육 로드맵"],
    },
    {
      icon: "Route",
      title: "교육로드맵 및 교육과정 개발",
      description: "직급·직무·역량 수준별 체계적 교육로드맵을 설계하고, ISD/ADDIE 모델 기반으로 현장 맞춤형 교육과정을 개발합니다.",
      methodology: "DACUM 직무분석 → Gap 진단 → ISD/ADDIE 기반 과정 설계 → 파일럿 검증",
      deliverables: ["교육로드맵", "훈련과정 설계서", "교재·교안", "평가도구"],
    },
    {
      icon: "Target",
      title: "교육운영 및 성과관리 체계 구축",
      description: "교육 실행 체계 설계, 학습성과 측정 프레임워크(Kirkpatrick 4단계) 구축, 교육 ROI 분석을 통한 지속적 품질 개선 체계를 수립합니다.",
      methodology: "Kirkpatrick 4단계 평가, 교육 ROI 분석, 학습관리시스템(LMS) 연계 설계",
      deliverables: ["교육운영 매뉴얼", "성과측정 프레임워크", "교육 효과성 분석 보고서"],
    },
    {
      icon: "RefreshCw",
      title: "직무·경력·조직 개발 컨설팅",
      description: "직무전환 진단, Skill Shift 분석, 경력개발경로(CDP) 설계, 조직학습 체계 구축까지. 개인과 조직의 역량 성장을 통합적으로 지원합니다.",
      methodology: "직무전환 Skill Mapping, 경력경로 설계, 조직개발(OD) 진단",
      deliverables: ["직무전환 분석 보고서", "CDP 설계서", "조직개발 로드맵"],
    },
    {
      icon: "BarChart3",
      title: "Skill 기반 인재개발",
      description: "Skill Taxonomy 설계, Skill Gap 진단(자가+상사 병행)을 통한 데이터 기반 학습경로 설계 및 조직 차원의 업스킬링·리스킬링 전략을 수립합니다.",
      methodology: "Skill Taxonomy 설계, 자가진단+상사진단 병행, 데이터 기반 Gap 분석, 러닝패스 알고리즘",
      deliverables: ["Skill Taxonomy", "Skill Gap 진단 보고서", "러닝패스 설계서", "Skill 맵"],
    },
  ],
  process: [
    { number: "01", title: "요구분석", description: "교육 니즈 및 Gap 파악" },
    { number: "02", title: "역량도출", description: "Skill/역량 체계 설계" },
    { number: "03", title: "과정개발", description: "교육과정 설계 및 개발" },
    { number: "04", title: "실행지원", description: "운영 및 효과성 분석" },
  ],
  stats: [
    { value: "60", suffix: "+", label: "교육체계·훈련과정 개발" },
    { value: "30", suffix: "+", label: "역량모델링 수행" },
    { value: "100", suffix: "+", label: "NCS·SQF 사업" },
    { value: "15", suffix: "yr+", label: "전문 수행 경력" },
  ],
  cta: { text: "HRD 솔루션 문의", href: "/contact" },
};

// ===== AX Service Detail =====
export const AX_SERVICE: ServiceData = {
  id: "ax",
  tag: "AX",
  tagColor: "navy",
  team: "AX컨설팅팀",
  title: "AX — AI Transformation 컨설팅",
  subtitle: "디지털 전환을 넘어, AI 전환으로",
  description:
    "기술이 아닌 사람을 중심에 둔 AI Transformation. HRM/HRD 전문성을 기반으로 조직의 AI 전환을 설계합니다.",
  items: [
    {
      icon: "ScanSearch",
      title: "AX(AI 전환) 수준 진단",
      description: "6차원 진단 프레임워크를 활용한 AI 성숙도 진단 및 업무 프로세스 AI 적용 가능 영역 분석",
      methodology: "6차원 성숙도 진단(전략·인재·프로세스·데이터·기술·문화), 경영진 인터뷰",
      deliverables: ["AX 진단 보고서", "성숙도 스코어카드", "갭 분석 리포트"],
    },
    {
      icon: "Map",
      title: "AX 전략 및 실행 로드맵 수립",
      description: "우선순위 유스케이스 선정 및 단계별 AI Transformation 로드맵 수립",
      methodology: "유스케이스 발굴 워크숍, Impact×Feasibility 우선순위 매트릭스",
      deliverables: ["AX 로드맵", "유스케이스 카탈로그", "투자 우선순위표"],
    },
    {
      icon: "BrainCircuit",
      title: "AI 역량 및 Skill Set 구축",
      description: "직급별 AI 리터러시 프로그램 설계 및 부트캠프/인증 체계 구축",
      methodology: "AI 리터러시 진단, 직급별 역량 체계, 부트캠프 설계",
      deliverables: ["AI Skill Set 체계표", "교육 커리큘럼", "인증 체계"],
    },
    {
      icon: "Workflow",
      title: "AI 활용 워크플로우 재설계",
      description: "프로세스별 AI 대체/보완/지원 영역 식별 및 업무 효율화 설계",
      methodology: "프로세스 마이닝, AI 적용 영역 식별(대체/보완/지원), PoC",
      deliverables: ["프로세스 분석서", "AI 적용 매트릭스", "재설계안"],
    },
    {
      icon: "Presentation",
      title: "AX 실행역량 강화 교육훈련(PBL)",
      description: "생성형 AI 활용, 프롬프트 엔지니어링, 바이브 코딩 등 PBL 기반 실무 교육",
      methodology: "실습 중심 커리큘럼, 직무별 AI 활용 시나리오 설계",
      deliverables: ["교육 커리큘럼", "실습 교재", "효과성 분석 보고서"],
    },
  ],
  process: [
    { number: "01", title: "AX 진단", description: "AI 성숙도 및 준비도 평가" },
    {
      number: "02",
      title: "전략수립",
      description: "로드맵 및 우선순위 도출",
    },
    {
      number: "03",
      title: "Skill 구축",
      description: "AI 역량 개발 및 교육",
    },
    {
      number: "04",
      title: "정착·고도화",
      description: "성과 측정 및 지속 개선",
    },
  ],
  stats: [
    { value: "HRM·HRD", suffix: "", label: "전문성 기반 AX 설계" },
    { value: "6", suffix: "차원", label: "AI 성숙도 진단 모델" },
    { value: "5", suffix: "단계", label: "AX 성숙도 프레임워크" },
    { value: "산업전환", suffix: "", label: "컨설팅 연계" },
  ],
  cta: { text: "AX 진단 의뢰", href: "/contact" },
};

// ===== AX Maturity Levels =====
export const AX_MATURITY_LEVELS = [
  { level: 1, name: "탐색", description: "AI에 대한 관심과 초기 학습 단계" },
  {
    level: 2,
    name: "시범",
    description: "파일럿 프로젝트를 통한 가능성 검증",
  },
  { level: 3, name: "도입", description: "핵심 업무에 AI 솔루션 본격 적용" },
  {
    level: 4,
    name: "내재화",
    description: "조직 전반의 AI 활용 문화 정착",
  },
  {
    level: 5,
    name: "지능화",
    description: "AI 기반 자율적 의사결정 및 혁신",
  },
];

// ===== Portfolio Projects =====
export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
  // === 2026 ===
  {
    id: 59,
    name: "컨소시엄 공동훈련 참여기업 AX(인공지능전환) 진단 컨설팅 도구 개발 용역",
    client: "한국산업인력공단",
    period: "2026.03 ~ 2026.12",
    year: 2026,
    category: "AX",
    status: "진행중",
    overview: "컨소시엄 공동훈련 참여기업 대상 AX(인공지능전환) 진단 컨설팅 도구 개발",
    tasks: ["AX 진단 도구 설계", "컨설팅 프레임워크 개발", "도구 검증 및 고도화"],
    results: ["AX 진단 컨설팅 도구 개발"],
    deliverables: ["AX 진단 도구", "컨설팅 매뉴얼", "활용 가이드"],
  },
  // === 2025 ===
  {
    id: 1,
    name: "과정평가형 자격 내부평가 매뉴얼 개발",
    client: "한국산업인력공단",
    period: "2025.08 ~ 2025.12",
    year: 2025,
    category: "HRD",
    status: "완료",
    overview: "과정평가형 국가기술자격의 내부평가 매뉴얼(가이드) 체계 개발",
    tasks: ["내부평가 기준 분석", "매뉴얼 설계", "가이드 개발"],
    results: ["내부평가 매뉴얼 체계 수립"],
    deliverables: ["내부평가 매뉴얼", "평가 가이드라인", "운영 지침서"],
  },
  {
    id: 2,
    name: "NCS 직무표준화 민간전문가 교육",
    client: "국군본부",
    period: "2025.04 ~ 2025.12",
    year: 2025,
    category: "HRD",
    status: "완료",
    overview: "군 직무표준화를 위한 NCS 기반 민간전문가 교육 프로그램 운영",
    tasks: ["교육과정 설계", "교육 운영", "성과 분석"],
    results: ["민간전문가 교육 수행"],
    deliverables: ["교육 커리큘럼", "교육 교재", "성과 보고서"],
  },
  {
    id: 3,
    name: "국가직무능력표준 교과 인정 컨설팅",
    client: "한국산업인력공단",
    period: "2025.04 ~ 2025.10",
    year: 2025,
    category: "HRD",
    status: "완료",
    overview: "NCS 기반 교과 인정 체계 컨설팅 및 품질관리",
    tasks: ["교과 인정 기준 분석", "컨설팅 수행", "품질관리"],
    results: ["교과 인정 체계 수립"],
    deliverables: ["교과 인정 컨설팅 보고서", "품질관리 가이드"],
  },
  {
    id: 4,
    name: "전기차 충전시설관리 교재 및 교안 개발",
    client: "한국자동차환경협회",
    period: "2025.05 ~ 2025.12",
    year: 2025,
    category: "HRD",
    status: "완료",
    overview: "전기차 충전시설 관리 안전보건체계 표준 교재 및 교안 개발",
    tasks: ["직무분석", "교재 설계", "교안 개발"],
    results: ["표준 교재·교안 체계 수립"],
    deliverables: ["표준 교재", "교안", "평가 도구"],
  },
  {
    id: 5,
    name: "기업수요 맞춤형 직무분석 및 훈련과정 개발",
    client: "대한상공회의소",
    period: "2025.06 ~ 2025.09",
    year: 2025,
    category: "HRD",
    status: "완료",
    overview: "기업 현장 직무분석을 기반으로 한 맞춤형 훈련과정 설계·개발",
    tasks: ["기업 직무분석", "훈련 니즈 분석", "과정 개발"],
    results: ["맞춤형 훈련과정 개발"],
    deliverables: ["직무분석 보고서", "훈련과정 설계서", "교재"],
  },
  {
    id: 6,
    name: "NCS·SQF 참여인력 역량향상 교육과정 운영",
    client: "한국산업인력공단",
    period: "2025.03 ~ 2025.11",
    year: 2025,
    category: "HRD",
    status: "완료",
    overview: "NCS 개발·개선 및 SQF 사업 참여인력 대상 역량향상 교육 운영",
    tasks: ["교육과정 설계", "교육 운영", "효과성 분석"],
    results: ["참여인력 역량향상 교육 수행"],
    deliverables: ["교육 커리큘럼", "교육 교재", "효과성 분석 보고서"],
  },
  {
    id: 7,
    name: "산업전환 협약기업 진단 및 맞춤형 훈련과정 개발",
    client: "한국화학융합시험연구원",
    period: "2025.04 ~ 2025.12",
    year: 2025,
    category: "HRD",
    status: "완료",
    overview: "산업전환 협약기업의 직무전환 진단 및 기업 맞춤형 훈련과정 개발",
    tasks: ["기업 진단", "직무전환 분석", "훈련과정 개발"],
    results: ["협약기업 진단 및 과정 개발"],
    deliverables: ["기업진단 보고서", "훈련과정 설계서", "교육 로드맵"],
  },
  {
    id: 8,
    name: "선도기업 전략직종 직무개발 직무디자인 연구",
    client: "한국장애인고용공단",
    period: "2025.04 ~ 2025.11",
    year: 2025,
    category: "HRM",
    status: "완료",
    overview: "선도기업 전략직종의 직무개발 및 직무디자인 연구",
    tasks: ["전략직종 분석", "직무개발", "직무디자인"],
    results: ["직무디자인 연구 수행"],
    deliverables: ["직무개발 보고서", "직무디자인 가이드"],
  },
  {
    id: 9,
    name: "지방공공기관 직무분석 및 교육훈련체계 구축",
    client: "지방공기업평가원",
    period: "2025.05 ~ 2025.10",
    year: 2025,
    category: "HRM",
    status: "완료",
    overview: "지방공공기관 직무분석 및 경력경로/교육훈련체계 구축 지원",
    tasks: ["직무분석", "경력경로 설계", "교육훈련체계 구축"],
    results: ["교육훈련체계 구축"],
    deliverables: ["직무분석 보고서", "경력경로 체계표", "교육훈련체계 보고서"],
  },
  {
    id: 10,
    name: "직무중심 인사관리체계 도입 컨설팅",
    client: "성남도시개발공사",
    period: "2025.08 ~ 2025.11",
    year: 2025,
    category: "HRM",
    status: "완료",
    overview: "직무중심 인사관리체계 도입을 위한 종합 컨설팅",
    tasks: ["현황 진단", "직무분석", "인사체계 설계"],
    results: ["인사관리체계 설계"],
    deliverables: ["직무분석 보고서", "인사관리체계 설계서"],
  },
  {
    id: 11,
    name: "환경영향평가사 자격 운영 방안 연구",
    client: "한국환경산업기술원",
    period: "2025.06 ~ 2025.11",
    year: 2025,
    category: "HRD",
    status: "완료",
    overview: "환경영향평가사 자격 활용 다변화 및 실무 중심 운영 방안 연구",
    tasks: ["자격 현황 분석", "활용 방안 연구", "제도 개선안 도출"],
    results: ["운영 방안 연구"],
    deliverables: ["연구 보고서", "제도 개선안"],
  },
  {
    id: 12,
    name: "과정평가형 자격 원형문제 파일럿테스트",
    client: "한국산업인력공단",
    period: "2025.07 ~ 2025.12",
    year: 2025,
    category: "HRD",
    status: "완료",
    overview: "과정평가형 국가기술자격 원형문제 파일럿테스트 수행",
    tasks: ["원형문제 분석", "파일럿테스트 설계", "테스트 수행"],
    results: ["파일럿테스트 수행"],
    deliverables: ["파일럿테스트 결과 보고서", "문제 분석 보고서"],
  },
  {
    id: 13,
    name: "직무분석 및 직무평가용역",
    client: "울산시설관리공단",
    period: "2025.07 ~ 2025.08",
    year: 2025,
    category: "HRM",
    status: "완료",
    overview: "시설관리공단 직무분석 및 직무평가 수행",
    tasks: ["직무조사", "직무분석", "직무평가"],
    results: ["직무분석 및 평가 완료"],
    deliverables: ["직무분석 보고서", "직무평가 결과표"],
  },
  {
    id: 14,
    name: "직무중심 인사관리 체계 구축",
    client: "경북문화재단",
    period: "2025.09 ~ 2025.12",
    year: 2025,
    category: "HRM",
    status: "완료",
    overview: "직무중심 인사관리 체계 구축을 위한 종합 컨설팅",
    tasks: ["직무분석", "인사체계 설계", "제도 구축"],
    results: ["인사관리체계 구축"],
    deliverables: ["직무분석 보고서", "인사관리체계 설계서"],
  },
  {
    id: 15,
    name: "NCS 활용 인사담당자 가이드 및 교육프로그램 개발",
    client: "한국산업인력공단",
    period: "2025.08 ~ 2025.12",
    year: 2025,
    category: "HRD",
    status: "완료",
    overview: "NCS 활용을 위한 인사담당자 가이드 및 교육프로그램 개발",
    tasks: ["가이드 설계", "교육프로그램 개발", "콘텐츠 제작"],
    results: ["가이드 및 프로그램 개발"],
    deliverables: ["인사담당자 가이드", "교육프로그램", "교육 교재"],
  },
  {
    id: 16,
    name: "위험물 분야 국가자격 신설 타당성 검증 연구",
    client: "소방청",
    period: "2025.09 ~ 2025.12",
    year: 2025,
    category: "HRD",
    status: "완료",
    overview: "위험물 분야 국가 기술·전문자격 신설 타당성 검증 연구",
    tasks: ["현황 분석", "타당성 검증", "신설안 도출"],
    results: ["타당성 검증 연구"],
    deliverables: ["연구 보고서", "자격 신설안"],
  },
  {
    id: 17,
    name: "코레일로지스 적정인력산정 및 조직진단",
    client: "코레일로지스",
    period: "2025.09 ~ 2026.01",
    year: 2025,
    category: "HRM",
    status: "완료",
    overview: "적정인력 산정 및 조직진단 컨설팅",
    tasks: ["조직진단", "업무량 조사", "적정인력 산정"],
    results: ["조직진단 및 인력산정"],
    deliverables: ["조직진단 보고서", "적정인력 산정 보고서"],
  },
  {
    id: 18,
    name: "학교법인 한국폴리텍 직무중심 보수체계 개편",
    client: "학교법인 한국폴리텍",
    period: "2025.11 ~ 2025.12",
    year: 2025,
    category: "HRM",
    status: "완료",
    overview: "직무중심 보수체계 개편을 위한 컨설팅",
    tasks: ["직무평가", "보수체계 설계", "개편안 수립"],
    results: ["보수체계 개편안 수립"],
    deliverables: ["직무평가 보고서", "보수체계 개편안"],
  },
  {
    id: 19,
    name: "GBSA 직무분석 및 적정인원 산정",
    client: "경기도경제과학진흥원",
    period: "2025.05 ~ 2025.09",
    year: 2025,
    category: "HRM",
    status: "완료",
    overview: "시설운영직 직무분석 및 적정인원 산정",
    tasks: ["직무분석", "업무량 조사", "적정인원 산정"],
    results: ["직무분석 및 인원 산정 완료"],
    deliverables: ["직무분석 보고서", "적정인원 산정 보고서"],
  },
  // === 2024 ===
  {
    id: 20,
    name: "NCS 기업활용 컨설팅 사업",
    client: "한국산업인력공단",
    period: "2024.03 ~ 2024.12",
    year: 2024,
    category: "HRD",
    status: "완료",
    overview: "NCS 기업활용 컨설팅 사업 수행 (기본형·확장형)",
    tasks: ["기업 진단", "NCS 활용 컨설팅", "성과 관리"],
    results: ["대규모 기업활용 컨설팅 완료"],
    deliverables: ["컨설팅 보고서", "NCS 활용 가이드", "성과 분석 보고서"],
  },
  {
    id: 21,
    name: "과정평가형 자격 내부평가 매뉴얼 개발",
    client: "한국산업인력공단",
    period: "2024.07 ~ 2024.12",
    year: 2024,
    category: "HRD",
    status: "완료",
    overview: "과정평가형 자격 내부평가 매뉴얼(가이드) 개발",
    tasks: ["평가 기준 분석", "매뉴얼 설계", "가이드 개발"],
    results: ["내부평가 매뉴얼 개발 완료"],
    deliverables: ["내부평가 매뉴얼", "평가 가이드"],
  },
  {
    id: 22,
    name: "NCS 직무표준화 민간전문가 교육",
    client: "국군본부",
    period: "2024.04 ~ 2024.12",
    year: 2024,
    category: "HRD",
    status: "완료",
    overview: "군 NCS 직무표준화를 위한 민간전문가 교육 운영",
    tasks: ["교육과정 설계", "교육 운영", "성과 평가"],
    results: ["민간전문가 교육 완료"],
    deliverables: ["교육 커리큘럼", "교재", "성과 보고서"],
  },
  {
    id: 23,
    name: "NCS·SQF 참여인력 역량향상 교육과정 운영",
    client: "한국산업인력공단",
    period: "2024.03 ~ 2024.11",
    year: 2024,
    category: "HRD",
    status: "완료",
    overview: "NCS 개발·개선 및 SQF 사업 참여인력 역량향상 교육 운영",
    tasks: ["교육과정 설계", "교육 운영", "효과성 분석"],
    results: ["역량향상 교육 완료"],
    deliverables: ["교육 커리큘럼", "교재", "효과성 보고서"],
  },
  {
    id: 24,
    name: "전기차 충전시설 관리 표준교재 개발 및 문제은행 구축",
    client: "한국자동차환경협회",
    period: "2024.05 ~ 2024.12",
    year: 2024,
    category: "HRD",
    status: "완료",
    overview: "전기차 충전시설 관리 분야 표준교재 개발 및 문제은행 구축",
    tasks: ["직무분석", "교재 개발", "문제은행 구축"],
    results: ["표준교재 및 문제은행 개발 완료"],
    deliverables: ["표준교재", "문제은행", "출제 가이드"],
  },
  {
    id: 25,
    name: "지방공공기관 경력경로 및 교육훈련체계 구축",
    client: "지방공기업평가원",
    period: "2024.05 ~ 2024.10",
    year: 2024,
    category: "HRM",
    status: "완료",
    overview: "지방공공기관 경력경로 및 교육훈련체계 구축 지원 컨설팅",
    tasks: ["직무분석", "경력경로 설계", "교육훈련체계 구축"],
    results: ["교육훈련체계 구축 완료"],
    deliverables: ["직무분석 보고서", "경력경로 체계표", "교육훈련체계 보고서"],
  },
  {
    id: 26,
    name: "강원랜드 직무분석 및 적정인력 산정",
    client: "강원랜드",
    period: "2024.06 ~ 2024.12",
    year: 2024,
    category: "HRM",
    status: "완료",
    overview: "전사 직무분석 및 적정인력 산정 컨설팅",
    tasks: ["직무조사", "직무분석", "적정인력 산정"],
    results: ["직무분석 및 적정인력 산정 완료"],
    deliverables: ["직무분석 보고서", "적정인력 산정 보고서", "직무기술서(JD)"],
  },
  {
    id: 27,
    name: "직무중심 조직진단 및 보수체계 고도화",
    client: "국토안전관리원",
    period: "2024.04 ~ 2024.10",
    year: 2024,
    category: "HRM",
    status: "완료",
    overview: "직무중심 조직진단 및 보수체계 고도화 컨설팅",
    tasks: ["조직진단", "직무분석", "보수체계 설계"],
    results: ["보수체계 고도화 완료"],
    deliverables: ["조직진단 보고서", "보수체계 설계서"],
  },
  {
    id: 28,
    name: "서울문화재단 직무중심인사관리체계 구축",
    client: "서울문화재단",
    period: "2024.06 ~ 2024.12",
    year: 2024,
    category: "HRM",
    status: "완료",
    overview: "직무중심 인사관리체계 구축을 위한 종합 컨설팅",
    tasks: ["직무분석", "인사체계 설계", "제도 구축"],
    results: ["인사관리체계 구축 완료"],
    deliverables: ["직무분석 보고서", "인사관리체계 설계서"],
  },
  {
    id: 29,
    name: "인천도시공사 직무중심 인사관리 체계 구축",
    client: "인천도시공사",
    period: "2024.07 ~ 2024.12",
    year: 2024,
    category: "HRM",
    status: "완료",
    overview: "직무중심 인사관리 체계 구축 컨설팅",
    tasks: ["직무분석", "직무평가", "인사체계 설계"],
    results: ["인사관리체계 구축 완료"],
    deliverables: ["직무분석 보고서", "직무평가 보고서", "인사체계 설계서"],
  },
  {
    id: 30,
    name: "부산도시공사 직무중심 인사관리 체계 설계",
    client: "부산도시공사",
    period: "2024.05 ~ 2024.11",
    year: 2024,
    category: "HRM",
    status: "완료",
    overview: "BMC 직무중심 인사관리 체계 설계 컨설팅",
    tasks: ["직무분석", "인사체계 설계", "제도 설계"],
    results: ["인사관리체계 설계 완료"],
    deliverables: ["직무분석 보고서", "인사관리체계 설계서"],
  },
  {
    id: 31,
    name: "기업수요 맞춤형 직무분석 및 훈련과정 개발",
    client: "대한상공회의소",
    period: "2024.06 ~ 2024.09",
    year: 2024,
    category: "HRD",
    status: "완료",
    overview: "기업 현장 직무분석 기반 맞춤형 훈련과정 개발",
    tasks: ["기업 직무분석", "훈련 니즈 분석", "과정 개발"],
    results: ["맞춤형 훈련과정 개발 완료"],
    deliverables: ["직무분석 보고서", "훈련과정 설계서", "교재"],
  },
  {
    id: 32,
    name: "기술교육로드맵 개발 및 신규과정 선정",
    client: "한국기술교육대학교",
    period: "2024.04 ~ 2024.10",
    year: 2024,
    category: "HRD",
    status: "완료",
    overview: "기술교육 로드맵 개발 및 신규 교육과정 선정 연구",
    tasks: ["교육 수요 분석", "로드맵 설계", "신규과정 선정"],
    results: ["교육로드맵 개발 완료"],
    deliverables: ["기술교육 로드맵", "신규과정 프로파일", "연구 보고서"],
  },
  {
    id: 33,
    name: "산업전환 협약기업 진단 및 훈련과정 개발",
    client: "한국화학융합시험연구원",
    period: "2024.05 ~ 2024.12",
    year: 2024,
    category: "HRD",
    status: "완료",
    overview: "산업전환 협약기업 진단 및 기업 맞춤형 훈련과정 개발",
    tasks: ["기업 진단", "직무전환 분석", "훈련과정 개발"],
    results: ["협약기업 진단 및 과정 개발 완료"],
    deliverables: ["기업진단 보고서", "훈련과정 설계서"],
  },
  {
    id: 34,
    name: "환경영향평가사 자격검정 제도 운영성과 분석",
    client: "한국환경산업기술원",
    period: "2024.06 ~ 2024.11",
    year: 2024,
    category: "HRD",
    status: "완료",
    overview: "환경영향평가사 자격검정 제도의 운영성과 분석 및 개선방안 마련",
    tasks: ["운영성과 분석", "제도 진단", "개선방안 도출"],
    results: ["제도 개선안 도출 완료"],
    deliverables: ["연구 보고서", "개선방안 보고서"],
  },
  {
    id: 35,
    name: "부산환경공단 직무분석 및 직무체계 구축",
    client: "부산환경공단",
    period: "2024.06 ~ 2024.11",
    year: 2024,
    category: "HRM",
    status: "완료",
    overview: "직무분석 및 직무체계 구축 컨설팅",
    tasks: ["직무조사", "직무분석", "직무체계 설계"],
    results: ["직무체계 구축 완료"],
    deliverables: ["직무분석 보고서", "직무체계 설계서"],
  },
  {
    id: 36,
    name: "대한법률구조공단 직무중심 보수체계 구축",
    client: "대한법률구조공단",
    period: "2024.06 ~ 2024.11",
    year: 2024,
    category: "HRM",
    status: "완료",
    overview: "직무중심의 보수체계 구축 컨설팅",
    tasks: ["직무평가", "보수체계 설계", "전환안 수립"],
    results: ["보수체계 구축 완료"],
    deliverables: ["직무평가 보고서", "보수체계 설계서"],
  },
  // === 2023 ===
  {
    id: 37,
    name: "NCS 기업활용 컨설팅 사업",
    client: "한국산업인력공단",
    period: "2023.03 ~ 2023.12",
    year: 2023,
    category: "HRD",
    status: "완료",
    overview: "NCS 기업활용 컨설팅 사업 수행 (확장형·기본형)",
    tasks: ["기업 진단", "NCS 활용 컨설팅", "성과 관리"],
    results: ["기업활용 컨설팅 완료"],
    deliverables: ["컨설팅 보고서", "NCS 활용 가이드"],
  },
  {
    id: 38,
    name: "과정평가형 자격 내부평가 매뉴얼 개발",
    client: "한국산업인력공단",
    period: "2023.07 ~ 2023.12",
    year: 2023,
    category: "HRD",
    status: "완료",
    overview: "과정평가형 자격 내부평가 매뉴얼 개발",
    tasks: ["평가 기준 분석", "매뉴얼 설계", "가이드 개발"],
    results: ["내부평가 매뉴얼 개발 완료"],
    deliverables: ["내부평가 매뉴얼", "평가 가이드"],
  },
  {
    id: 39,
    name: "기업수요 맞춤형 직무분석 및 훈련과정 개발",
    client: "대한상공회의소",
    period: "2023.04 ~ 2023.09",
    year: 2023,
    category: "HRD",
    status: "완료",
    overview: "기업 현장 직무분석 기반 맞춤형 훈련과정 설계·개발",
    tasks: ["기업 직무분석", "훈련 니즈 분석", "과정 개발"],
    results: ["맞춤형 훈련과정 개발 완료"],
    deliverables: ["직무분석 보고서", "훈련과정 설계서", "교재"],
  },
  {
    id: 40,
    name: "NCS 직무표준화 민간전문가 교육",
    client: "국군본부",
    period: "2023.04 ~ 2023.12",
    year: 2023,
    category: "HRD",
    status: "완료",
    overview: "군 NCS 직무표준화를 위한 민간전문가 교육 운영",
    tasks: ["교육과정 설계", "교육 운영", "성과 평가"],
    results: ["민간전문가 교육 완료"],
    deliverables: ["교육 커리큘럼", "교재", "성과 보고서"],
  },
  {
    id: 41,
    name: "산업전환 기업맞춤형 진단 및 훈련과정 개발",
    client: "대한상공회의소",
    period: "2023.05 ~ 2023.11",
    year: 2023,
    category: "HRD",
    status: "완료",
    overview: "산업전환 기업맞춤형 진단 및 훈련과정 개발",
    tasks: ["기업 진단", "직무전환 분석", "훈련과정 개발"],
    results: ["진단 및 과정 개발 완료"],
    deliverables: ["기업진단 보고서", "훈련과정 설계서"],
  },
  {
    id: 42,
    name: "SK에너지 산업전환 직무전환 컨설팅",
    client: "SK에너지",
    period: "2023.06 ~ 2023.11",
    year: 2023,
    category: "HRD",
    status: "완료",
    overview: "산업전환 공동훈련센터 협약기업 직무전환 컨설팅",
    tasks: ["직무전환 진단", "교육 설계", "컨설팅 수행"],
    results: ["직무전환 컨설팅 완료"],
    deliverables: ["직무전환 진단 보고서", "교육 설계서"],
  },
  {
    id: 43,
    name: "NCS 활용 지방공공기관 직무분석 지원",
    client: "지방공기업평가원",
    period: "2023.05 ~ 2023.10",
    year: 2023,
    category: "HRM",
    status: "완료",
    overview: "NCS를 활용한 지방공공기관 직무분석 지원 컨설팅",
    tasks: ["직무분석", "NCS 매핑", "직무기술서 작성"],
    results: ["직무분석 지원 완료"],
    deliverables: ["직무분석 보고서", "직무기술서(JD)", "NCS 매핑표"],
  },
  {
    id: 44,
    name: "한국콘텐츠진흥원 직무중심 보수체계 설계",
    client: "한국콘텐츠진흥원",
    period: "2023.06 ~ 2023.11",
    year: 2023,
    category: "HRM",
    status: "완료",
    overview: "직무중심 보수체계 설계 고도화 컨설팅",
    tasks: ["직무평가", "보수체계 설계", "시뮬레이션"],
    results: ["보수체계 설계 완료"],
    deliverables: ["직무평가 보고서", "보수체계 설계서", "시뮬레이션 결과"],
  },
  {
    id: 45,
    name: "연구기관 인재개발 컨설팅",
    client: "국가과학기술인력개발원",
    period: "2023.04 ~ 2023.12",
    year: 2023,
    category: "HRD",
    status: "완료",
    overview: "연구기관 인재개발 컨설팅 수행 및 성과측정 방안 기획",
    tasks: ["교육 니즈 분석", "인재개발 컨설팅", "성과측정 설계"],
    results: ["인재개발 컨설팅 완료"],
    deliverables: ["인재개발 컨설팅 보고서", "성과측정 방안"],
  },
  {
    id: 46,
    name: "KG모빌리티 직급제도 및 수당체계 개편",
    client: "KG모빌리티",
    period: "2023.07 ~ 2023.12",
    year: 2023,
    category: "HRM",
    status: "완료",
    overview: "직급제도 및 수당체계 개편 컨설팅(직무분석 기반)",
    tasks: ["직무분석", "직급제도 설계", "수당체계 개편"],
    results: ["제도 개편 완료"],
    deliverables: ["직무분석 보고서", "직급제도 설계서", "수당체계 개편안"],
  },
  // === 2022 ===
  {
    id: 47,
    name: "기업수요 맞춤형 직무분석 및 훈련과정 개발",
    client: "대한상공회의소",
    period: "2022.04 ~ 2022.09",
    year: 2022,
    category: "HRD",
    status: "완료",
    overview: "기업 현장 직무분석 기반 맞춤형 훈련과정 설계·개발",
    tasks: ["기업 직무분석", "훈련 니즈 분석", "과정 개발"],
    results: ["맞춤형 훈련과정 개발 완료"],
    deliverables: ["직무분석 보고서", "훈련과정 설계서", "교재"],
  },
  {
    id: 48,
    name: "NCS 기업활용 컨설팅 사업",
    client: "한국산업인력공단",
    period: "2022.03 ~ 2022.12",
    year: 2022,
    category: "HRD",
    status: "완료",
    overview: "NCS 기업활용 컨설팅 사업 수행 (기본형·확장형)",
    tasks: ["기업 진단", "NCS 활용 컨설팅", "성과 관리"],
    results: ["기업활용 컨설팅 완료"],
    deliverables: ["컨설팅 보고서", "NCS 활용 가이드"],
  },
  {
    id: 49,
    name: "과정평가형 자격 내부평가 매뉴얼 개발",
    client: "한국산업인력공단",
    period: "2022.07 ~ 2022.12",
    year: 2022,
    category: "HRD",
    status: "완료",
    overview: "과정평가형 자격 내부평가 매뉴얼 개발",
    tasks: ["평가 기준 분석", "매뉴얼 설계", "가이드 개발"],
    results: ["내부평가 매뉴얼 개발 완료"],
    deliverables: ["내부평가 매뉴얼", "평가 가이드"],
  },
  {
    id: 50,
    name: "산업전환 기업맞춤형 진단 및 훈련과정 개발",
    client: "대한상공회의소",
    period: "2022.05 ~ 2022.11",
    year: 2022,
    category: "HRD",
    status: "완료",
    overview: "산업전환 기업 맞춤형 진단 및 훈련과정 개발",
    tasks: ["기업 진단", "직무전환 분석", "훈련과정 개발"],
    results: ["진단 및 과정 개발 완료"],
    deliverables: ["기업진단 보고서", "훈련과정 설계서"],
  },
  {
    id: 51,
    name: "NCS 직무표준화 민간전문가 교육",
    client: "국군본부",
    period: "2022.04 ~ 2022.12",
    year: 2022,
    category: "HRD",
    status: "완료",
    overview: "군 NCS 직무표준화를 위한 민간전문가 교육 운영",
    tasks: ["교육과정 설계", "교육 운영", "성과 평가"],
    results: ["민간전문가 교육 완료"],
    deliverables: ["교육 커리큘럼", "교재", "성과 보고서"],
  },
  {
    id: 52,
    name: "SK에너지 산업전환 직무전환 컨설팅",
    client: "SK에너지",
    period: "2022.06 ~ 2022.11",
    year: 2022,
    category: "HRD",
    status: "완료",
    overview: "산업전환 공동훈련센터 협약기업 직무전환 컨설팅",
    tasks: ["직무전환 진단", "교육 설계", "컨설팅 수행"],
    results: ["직무전환 컨설팅 완료"],
    deliverables: ["직무전환 진단 보고서", "교육 설계서"],
  },
  {
    id: 53,
    name: "금호타이어 직무분석을 통한 업무효율화",
    client: "금호타이어",
    period: "2022.05 ~ 2022.10",
    year: 2022,
    category: "HRM",
    status: "완료",
    overview: "일반직 직무분석을 통한 업무효율화 프로젝트",
    tasks: ["직무조사", "직무분석", "업무효율화 방안 도출"],
    results: ["직무분석 및 업무효율화 완료"],
    deliverables: ["직무분석 보고서", "업무효율화 방안"],
  },
  {
    id: 54,
    name: "세라젬 직무분석 및 적정인력 산정",
    client: "세라젬",
    period: "2022.06 ~ 2022.11",
    year: 2022,
    category: "HRM",
    status: "완료",
    overview: "사무직 직무분석 및 적정인력 산정 컨설팅",
    tasks: ["직무조사", "직무분석", "적정인력 산정"],
    results: ["직무분석 및 인력산정 완료"],
    deliverables: ["직무분석 보고서", "적정인력 산정 보고서"],
  },
  {
    id: 55,
    name: "국토안전관리원 조직진단 및 인력운영 효율화",
    client: "국토안전관리원",
    period: "2022.04 ~ 2022.10",
    year: 2022,
    category: "HRM",
    status: "완료",
    overview: "조직진단 및 인력운영 효율화 방안 수립 컨설팅",
    tasks: ["조직진단", "인력분석", "효율화 방안 수립"],
    results: ["조직진단 및 효율화 방안 수립 완료"],
    deliverables: ["조직진단 보고서", "인력운영 효율화 보고서"],
  },
  {
    id: 56,
    name: "한국노동연구원 직무중심 인사관리체계 도입",
    client: "한국노동연구원",
    period: "2022.05 ~ 2022.10",
    year: 2022,
    category: "HRM",
    status: "완료",
    overview: "직무중심 인사관리체계 도입 컨설팅",
    tasks: ["직무분석", "인사체계 설계", "제도 도입"],
    results: ["인사관리체계 도입 완료"],
    deliverables: ["직무분석 보고서", "인사관리체계 설계서"],
  },
  {
    id: 57,
    name: "연구기관 인재개발 컨설팅",
    client: "국가과학기술인력개발원",
    period: "2022.04 ~ 2022.12",
    year: 2022,
    category: "HRD",
    status: "완료",
    overview: "연구기관 인재개발 컨설팅 수행 및 서비스 기반 확대",
    tasks: ["교육 니즈 분석", "인재개발 컨설팅", "서비스 설계"],
    results: ["인재개발 컨설팅 완료"],
    deliverables: ["인재개발 컨설팅 보고서", "서비스 기반 확대 방안"],
  },
  {
    id: 58,
    name: "스마트 건설 NCS 및 국가기술자격 개발연구",
    client: "한국도로공사",
    period: "2022.05 ~ 2022.11",
    year: 2022,
    category: "HRD",
    status: "완료",
    overview: "스마트 건설 분야 NCS 및 국가기술자격 개발 연구",
    tasks: ["NCS 분석", "자격 개발 연구", "가이드 작성"],
    results: ["NCS 및 자격 개발 연구 완료"],
    deliverables: ["NCS 개발 보고서", "자격 개발 연구 보고서"],
  },
];

// ===== Portfolio Filter Categories =====
export const PORTFOLIO_FILTERS = [
  { key: "all", label: "전체" },
  { key: "HRM", label: "HRM" },
  { key: "HRD", label: "HRD" },
  { key: "AX", label: "AX" },
];

// ===== Portfolio Year Filters =====
export const PORTFOLIO_YEARS = [2026, 2025, 2024, 2023, 2022];

// ===== FAQ =====
export const FAQ_ITEMS: FAQItem[] = [
  {
    question: "컨설팅 기간은 보통 얼마나 걸리나요?",
    answer:
      "프로젝트 규모와 범위에 따라 다르지만, 일반적으로 직무분석은 3~6개월, 교육체계 수립은 2~4개월, AX 진단은 1~2개월 정도 소요됩니다. 초기 상담 시 보다 정확한 일정을 안내해 드립니다.",
  },
  {
    question: "컨설팅 비용은 어떻게 산정되나요?",
    answer:
      "프로젝트의 범위, 기간, 투입 인력 등을 종합적으로 고려하여 산정합니다. 공공기관의 경우 용역 예산 규모에 맞춰 최적의 컨설팅 범위를 설계해 드립니다. 무료 상담을 통해 견적을 받아보실 수 있습니다.",
  },
  {
    question: "공공기관 외에 민간기업도 컨설팅 가능한가요?",
    answer:
      "네, 가능합니다. 시앤피컨설팅은 공공기관 특화 경험을 바탕으로 민간기업에도 직무분석, 역량모델링, AX 컨설팅 등 다양한 서비스를 제공하고 있습니다.",
  },
  {
    question: "컨설팅 프로세스는 어떻게 진행되나요?",
    answer:
      "일반적으로 ①현황진단 → ②분석·설계 → ③실행·구축 → ④정착·지원의 4단계로 진행됩니다. 각 단계마다 중간보고를 통해 진행 상황을 공유하고, 고객의 피드백을 반영합니다.",
  },
  {
    question: "원격 컨설팅도 가능한가요?",
    answer:
      "네, 화상회의, 온라인 워크숍, 클라우드 기반 협업 도구를 활용한 원격 컨설팅이 가능합니다. 다만, 직무분석 인터뷰 등 일부 과정은 현장 방문이 필요할 수 있습니다.",
  },
  {
    question: "직무분석은 왜 필요한가요?",
    answer:
      "직무분석은 직무급 전환, 성과관리, 조직설계, 교육체계 수립 등 모든 HR 제도의 기초입니다. 기재부 가이드라인에 따라 공공기관의 직무급 전환이 의무화되면서, 체계적인 직무분석의 중요성이 더욱 높아지고 있습니다.",
  },
  {
    question: "역량모델링과 Skill 기반 인재개발의 차이는 무엇인가요?",
    answer:
      "역량모델링은 조직의 핵심역량·리더십역량·직무역량을 도출하고 행동지표를 정의하는 것이고, Skill 기반 접근은 개인의 구체적 스킬을 측정·진단하여 학습경로를 설계하는 것입니다. 시앤피컨설팅은 두 접근을 통합하여 역량 체계 위에 Skill Gap 분석과 맞춤형 학습설계를 연계합니다.",
  },
  {
    question: "AX(AI Transformation)와 DX(Digital Transformation)는 어떻게 다른가요?",
    answer:
      "DX가 업무의 디지털화에 초점을 맞춘다면, AX는 AI를 활용한 업무 프로세스의 근본적 재설계와 구성원의 AI 역량 구축까지 포괄합니다. 시앤피컨설팅의 AX 컨설팅은 HRM/HRD 전문성을 기반으로 '사람 중심의 AI 전환'을 설계합니다.",
  },
  {
    question: "주요 산출물에는 어떤 것들이 있나요?",
    answer:
      "프로젝트 유형에 따라 직무분석 보고서, 직무기술서(JD), 직무분류체계표, 역량모델·역량사전, 교육체계도, 교육과정 프로파일, KPI 체계표, AX 진단 보고서, AI 전환 로드맵 등 다양한 산출물을 제공합니다.",
  },
  {
    question: "경영평가 대응은 어떻게 지원하나요?",
    answer:
      "인사 분야 경영평가 지표를 분석하고, 지표별 체계적 대응 전략을 수립합니다. 증빙 체계 구축, 실적 관리 매뉴얼 제공, 평가 모의 진단까지 지원하며, 다수의 공공기관에서 A등급 달성을 지원한 경험이 있습니다.",
  },
];

// ===== About - Timeline =====
export const TIMELINE: TimelineItem[] = [
  { year: "2010", events: ["시앤피컨설팅 설립", "HR 컨설팅 사업 개시"] },
  {
    year: "2013",
    events: ["공공기관 컨설팅 100건 달성", "NCS 기반 교육과정 개발 시작"],
  },
  {
    year: "2016",
    events: [
      "직업능력컨설팅본부 신설",
      "한국산업인력공단 파트너십 체결",
    ],
  },
  {
    year: "2019",
    events: ["컨설팅 수행 300건 돌파", "역량모델링 전문 조직 확대"],
  },
  {
    year: "2022",
    events: ["디지털 전환(DX) 컨설팅 사업 개시", "Skill 기반 HRD 체계 도입"],
  },
  {
    year: "2024",
    events: [
      "AX(AI Transformation) 컨설팅 사업 본격화",
      "컨설팅 수행 500건 돌파",
    ],
  },
  {
    year: "2025",
    events: ["AX 진단 프레임워크 개발", "AI 교육훈련 프로그램 런칭"],
  },
];

// ===== About - Organization (8 divisions) =====
export const DIVISIONS = [
  "직업능력컨설팅본부",
  "경영전략본부",
  "글로벌개발연구원",
  "HRD사업본부",
  "NCS사업본부",
  "ODA사업본부",
  "조사연구본부",
  "Career Consulting본부",
];

// ===== Teams =====
export const TEAMS: Team[] = [
  {
    id: "hrm-team",
    name: "공공기관컨설팅팀",
    description:
      "공공기관 직무분석, 직무평가, 보수체계, 조직설계 등 HRM 전 영역의 컨설팅을 수행합니다.",
    serviceArea: "HRM",
  },
  {
    id: "hrd-team",
    name: "HR솔루션팀",
    description:
      "역량모델링, NCS 기반 교육체계, Skill Gap 분석, 학습경로 설계 등 인재개발 솔루션을 제공합니다.",
    serviceArea: "HRD",
  },
  {
    id: "ax-team",
    name: "AX컨설팅팀",
    description:
      "AI 성숙도 진단, AX 전략수립, Skill Set 구축, AI 워크플로우 재설계 등 사람 중심 AI 전환을 설계합니다.",
    serviceArea: "AX",
  },
];

// ===== Featured Clients (홈 Trust Strip) =====
export const CLIENTS_FEATURED: FeaturedClient[] = [
  { name: "한국산업인력공단", category: "HRD" },
  { name: "대한상공회의소", category: "HRD" },
  { name: "강원랜드", category: "HRM" },
  { name: "SK에너지", category: "HRD" },
  { name: "한국도로공사", category: "HRD" },
  { name: "인천도시공사", category: "HRM" },
  { name: "지방공기업평가원", category: "HRM" },
  { name: "국토안전관리원", category: "HRM" },
  { name: "한국장애인고용공단", category: "HRM" },
  { name: "한국폴리텍", category: "HRM" },
  { name: "금호타이어", category: "HRM" },
  { name: "세라젬", category: "HRM" },
  { name: "KG모빌리티", category: "HRM" },
  { name: "소방청", category: "HRD" },
  { name: "한국환경산업기술원", category: "HRD" },
  { name: "코레일로지스", category: "HRM" },
  { name: "서울문화재단", category: "HRM" },
  { name: "부산도시공사", category: "HRM" },
  { name: "한국콘텐츠진흥원", category: "HRM" },
  { name: "한국화학융합시험연구원", category: "HRD" },
  { name: "경북문화재단", category: "HRM" },
  { name: "성남도시개발공사", category: "HRM" },
  { name: "한국기술교육대학교", category: "HRD" },
  { name: "대한법률구조공단", category: "HRM" },
  { name: "부산환경공단", category: "HRM" },
  { name: "한국노동연구원", category: "HRM" },
  { name: "경기도경제과학진흥원", category: "HRM" },
  { name: "울산시설관리공단", category: "HRM" },
  { name: "국가과학기술인력개발원", category: "HRD" },
  { name: "한국자동차환경협회", category: "HRD" },
];

// ===== AX Maturity Diagnostic Questions =====
export const AX_DIAGNOSTIC_QUESTIONS: MaturityQuestion[] = [
  {
    id: 1,
    dimension: "전략",
    question: "우리 조직에 AI 전환(AX) 전략이 있나요?",
    options: [
      { label: "AI에 대한 논의가 거의 없다", score: 1 },
      { label: "관심은 있으나 구체적 전략은 없다", score: 2 },
      { label: "부서 단위 AI 활용 계획이 있다", score: 3 },
      { label: "전사 AX 로드맵이 수립되어 있다", score: 4 },
      { label: "AX 전략이 경영전략에 통합되어 있다", score: 5 },
    ],
  },
  {
    id: 2,
    dimension: "인재",
    question: "구성원의 AI 활용 역량 수준은?",
    options: [
      { label: "대부분 AI 도구를 사용하지 않는다", score: 1 },
      { label: "일부 직원만 개별적으로 활용한다", score: 2 },
      { label: "기본 AI 리터러시 교육을 실시했다", score: 3 },
      { label: "직급별 체계적 AI 교육을 운영 중이다", score: 4 },
      { label: "전 직원이 업무에 AI를 자연스럽게 활용한다", score: 5 },
    ],
  },
  {
    id: 3,
    dimension: "프로세스",
    question: "업무 프로세스에 AI가 얼마나 적용되어 있나요?",
    options: [
      { label: "AI가 적용된 업무 프로세스가 없다", score: 1 },
      { label: "1~2개 파일럿 수준으로 시도 중이다", score: 2 },
      { label: "핵심 업무 일부에 AI를 적용했다", score: 3 },
      { label: "대부분의 주요 업무에 AI가 통합되었다", score: 4 },
      { label: "AI 기반으로 업무 프로세스가 자동화되었다", score: 5 },
    ],
  },
  {
    id: 4,
    dimension: "데이터",
    question: "AI 활용을 위한 데이터 인프라 수준은?",
    options: [
      { label: "데이터가 부서별로 분산되어 있다", score: 1 },
      { label: "일부 데이터를 수집·정리하기 시작했다", score: 2 },
      { label: "주요 데이터가 통합·관리되고 있다", score: 3 },
      { label: "데이터 품질 관리 체계가 운영 중이다", score: 4 },
      { label: "실시간 데이터 기반 의사결정이 가능하다", score: 5 },
    ],
  },
  {
    id: 5,
    dimension: "기술",
    question: "우리 조직의 AI 기술 인프라 수준은?",
    options: [
      { label: "AI 관련 기술 인프라가 전혀 없다", score: 1 },
      { label: "기본적인 클라우드/데이터 인프라가 있다", score: 2 },
      { label: "AI 도구를 일부 도입하여 시범 운영 중이다", score: 3 },
      { label: "조직 전반에 AI 플랫폼이 구축되어 있다", score: 4 },
      { label: "자체 AI 모델을 개발·운영하며 지속 고도화하고 있다", score: 5 },
    ],
  },
  {
    id: 6,
    dimension: "문화",
    question: "조직의 AI 전환에 대한 문화와 인식은?",
    options: [
      { label: "AI에 대한 거부감·불안감이 크다", score: 1 },
      { label: "관심은 있으나 적극적이지 않다", score: 2 },
      { label: "변화에 긍정적이고 시도를 장려한다", score: 3 },
      { label: "AI 활용 성과를 공유하고 확산한다", score: 4 },
      { label: "AI 혁신이 조직 문화로 정착되었다", score: 5 },
    ],
  },
];

// ===== HRM Pain Points =====
export const HRM_PAIN_POINTS = [
  {
    icon: "AlertTriangle",
    title: "연공급 체계의 한계",
    description:
      "직무 가치와 무관한 보상 체계로 인한 우수인재 이탈과 동기부여 저하",
  },
  {
    icon: "FileWarning",
    title: "직무체계 부재",
    description:
      "체계적 직무분류와 직무등급 없이 인사제도 운영의 일관성 확보 어려움",
  },
  {
    icon: "Clock",
    title: "성과관리 고도화 필요",
    description:
      "직무 중심 성과지표(KPI) 설계 및 공정한 평가체계 구축 필요",
  },
];

// ===== Public HR Service Detail =====
export const PUBLIC_HR_SERVICE: ServiceData = {
  id: "public-hr",
  tag: "공공HR",
  tagColor: "navy",
  team: "공공기관컨설팅팀",
  title: "공공기관 HR 컨설팅",
  subtitle: "직무급 전환, 경영평가 대응의 파트너",
  description:
    "공공기관 직무중심 인사제도 개편(채용·평가·직무급 등), 조직·인력 운영진단, 중장기 경영전략 수립, 경영평가 대응까지. 공공부문 HR 혁신의 전 과정을 체계적으로 지원합니다.",
  items: [
    {
      icon: "Landmark",
      title: "직무중심 인사제도 개편",
      description: "채용·평가·직무급 등 공공기관 인사제도를 직무 중심으로 전면 개편 설계",
      methodology: "직무분석, 직무평가, 직무급 전환 시뮬레이션, 기재부 가이드라인 연계",
      deliverables: ["인사제도 개편안", "직무급 전환 로드맵", "채용·평가체계 설계서"],
    },
    {
      icon: "SearchCheck",
      title: "조직·인력 운영진단",
      description: "조직 기능분석, 업무량 조사, 적정인력 산정을 통한 조직 효율성 진단",
      methodology: "기능분석, 업무량 조사, 인력운영 실태분석, BPR",
      deliverables: ["조직진단 보고서", "적정인력 산정 결과", "조직개편 권고안"],
    },
    {
      icon: "TrendingUp",
      title: "중장기 경영전략 수립",
      description: "비전·미션 재정립, 전략목표 체계 설계, 실행과제 도출 및 로드맵 수립",
      methodology: "환경분석(SWOT), BSC 전략체계, 전략 워크숍, 실행과제 우선순위 도출",
      deliverables: ["중장기 경영전략 보고서", "전략목표 체계표", "실행 로드맵"],
    },
    {
      icon: "Award",
      title: "경영평가 대응 지원",
      description: "기획재정부 경영평가 지표 분석 및 인사 분야 체계적 대응 전략 수립",
      methodology: "경영평가 지표 분석, 이행실적 점검, 개선과제 도출",
      deliverables: ["경영평가 대응 보고서", "지표별 이행계획", "개선과제 목록"],
    },
  ],
  process: [
    { number: "01", title: "진단", description: "현황 분석 및 이슈 도출" },
    { number: "02", title: "설계", description: "제도·전략 설계" },
    { number: "03", title: "도입", description: "시범 적용 및 조정" },
    { number: "04", title: "안정화", description: "정착 지원 및 모니터링" },
  ],
  stats: [
    { value: "40", suffix: "+", label: "공공기관 인사컨설팅" },
    { value: "30", suffix: "+", label: "직무급 전환 컨설팅" },
    { value: "20", suffix: "+", label: "경영전략·조직진단" },
    { value: "15", suffix: "yr+", label: "전문 수행 경력" },
  ],
  cta: { text: "공공기관 HR 컨설팅 상담", href: "/contact" },
};

export const PUBLIC_HR_PAIN_POINTS = [
  {
    icon: "AlertTriangle",
    title: "직무급 전환 의무",
    description:
      "기재부 가이드라인에 따른 직무급 전환 로드맵 수립 시급",
  },
  {
    icon: "FileWarning",
    title: "경영평가 대응 부담",
    description:
      "매년 강화되는 인사 분야 경영평가 지표에 대한 체계적 대응 필요",
  },
  {
    icon: "Clock",
    title: "조직 효율성 저하",
    description:
      "기능 중복, 인력 배치 비효율로 인한 조직 운영 최적화 필요",
  },
];

// ===== HRD Pain Points =====
export const HRD_PAIN_POINTS = [
  {
    icon: "AlertTriangle",
    title: "체계 없는 교육훈련",
    description:
      "NCS·SQF 연계 없이 운영되는 교육과정, 직무와 교육 간 괴리로 훈련 효과성 미흡",
  },
  {
    icon: "FileWarning",
    title: "역량 진단·평가의 부재",
    description:
      "BEI·DACUM 등 검증된 방법론 없이 역량모델이 형식적 수준에 머물러 인재개발 전략 수립 곤란",
  },
  {
    icon: "Clock",
    title: "Skill Gap 대응 시급",
    description:
      "산업전환·디지털화에 따른 업스킬링/리스킬링 수요 증가, 데이터 기반 학습경로 설계 필요",
  },
];
